use crate::ast::{Expr, AddOp, MulOp, RelOp, Direction, Variable};

grammar;

pub Expr: Box<Expr> = {
    <e:LetRec> => e,
};

LetRec: Box<Expr> = {
    <e:Let> => e,
    "letrec" <x:Variable> "=" <evar:LetRec> "in" <ebody:LetRec> => {
        let xclone = x.clone();
        let lam = Box::new(Expr::Lam { x: xclone, e: ebody });
        let arg = Box::new(Expr::Fix { x, e: evar });
        Box::new(Expr::App { lam, arg })
    }
};

Let: Box<Expr> = {
    <e:Func> => e,
    "let" <x:Variable> "=" <e_x:Let> "in" <e_in:Let> => Box::new(Expr::Let { x, e_x, e_in }),
};

Func: Box<Expr> = {
    <e:Fix> => e,
    "fun" <x:Variable> "->" <e:Func> => Box::new(Expr::Lam { x, e }),
};

Fix: Box<Expr> = {
    <e:App> => e,
    "fix" <x:Variable> "->" <e:Fix> => Box::new(Expr::Fix { x, e }),
};

App: Box<Expr> = {
    <e:If> => e,
    <lam:App> <arg:If> => Box::new(Expr::App { lam, arg }),
};

If: Box<Expr> = {
    <e:Case> => e,
    "if" <cond:Case> "then" <then_:Case> "else" <else_:Case> => Box::new(Expr::If { cond, then_, else_ }),
};

Case: Box<Expr> = {
    <e:Inject> => e,
    "case" <e:Case> "{" "L" "(" <xleft:Variable> ")" "->" <eleft:Case> "|" "R" "(" <xright:Variable> ")" "->" <eright:Case> "}" => Box::new(Expr::Case { e, xleft, eleft, xright, eright }),
};

Inject: Box<Expr> = {
    <e:Project> => e,
    "inj" <e:Project> "=" <d:Direction> => Box::new(Expr::Inject { e, d }),
};

Project: Box<Expr> = {
    <e:OrExpr> => e,
    <e:OrExpr> "." <d:Direction> => Box::new(Expr::Project { e, d }),
};

OrExpr: Box<Expr> = {
    <e:AndExpr> => e,
    <left:OrExpr> "||" <right:AndExpr> => Box::new(Expr::Or { left, right }),
};

AndExpr: Box<Expr> = {
    <e:RelExpr> => e,
    <left:AndExpr> "&&" <right:RelExpr> => Box::new(Expr::And { left, right }),
};

RelExpr: Box<Expr> = {
    <e:AddExpr> => e,
    <left:RelExpr> <relop:RelOp> <right:AddExpr> => Box::new(Expr::Relop { relop, left, right }),
};

AddExpr: Box<Expr> = {
    <e:MulExpr> => e,
    <left:AddExpr> <binop:AddOp> <right:MulExpr> => Box::new(Expr::Addop { binop, left, right }),
};

MulExpr: Box<Expr> = {
    <e:PrimaryExpr> => e,
    <left:MulExpr> <binop:MulOp> <right:PrimaryExpr> => Box::new(Expr::Mulop { binop, left, right }),
};

PrimaryExpr: Box<Expr> = {
    "(" <e:Expr> ")" => e,
    "(" <left:Expr> "," <right:Expr> ")" => Box::new(Expr::Pair { left, right }),

    <n:NUM> => Box::new(Expr::Num(n)),
    <v:Variable> => Box::new(Expr::Var(v)),
    "true" => Box::new(Expr::True),
    "false" => Box::new(Expr::False),
    "(" ")" => Box::new(Expr::Unit),
}

AddOp: AddOp = {
    "+" => AddOp::Add,
    "-" => AddOp::Sub,
};

MulOp: MulOp = {
    "*" => MulOp::Mul,
    "/" => MulOp::Div,
};

RelOp: RelOp = {
    "==" => RelOp::Eq,
    ">" => RelOp::Gt,
    "<" => RelOp::Lt,
};

Direction: Direction = {
    "L" => Direction::Left,
    "R" => Direction::Right,
};

Variable: Variable = {
    <v:r"[a-zA-Z][a-zA-Z0-9_]*"> => Variable(v.to_string()),
};

NUM: i32 = {
    <n:r"[0-9]+"> => n.parse().unwrap(),
};